### ISSUE TITLE
Kubernetes Helm MVU testing log

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/deploy-sourcegraph-helm#249]
## This issue tracks a multi-version upgrade using the at `sourcegraph-migrator` helm chart currently undocumented in main docs

**Comment by DaedalusG** [comment]
A Sourcegraph instance was provisioned using terraform from the following repo: https://github.com/sourcegraph/terraform-dev-replicas/tree/main/template/gcp/kubernetes

**/Users/warrengifford/terraform-dev-replicas/template/gcp/kubernetes/resources/override.yaml**
```
storageClass:
  create: true
  type: pd-ssd # This configures SSDs (recommended).
  provisioner: pd.csi.storage.gke.io
  volumeBindingMode: WaitForFirstConsumer
  reclaimPolicy: Delete
frontend:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: null
      nginx.ingress.kubernetes.io/proxy-body-size: 150m
    host: sourcegraph.warren.com
    ingressClassName: nginx-helm
  resources:
    limits:
      cpu: '1.5'
      memory: 3G
    requests:
      cpu: '1'
      memory: 1.5G
gitserver:
  replicaCount: 1
  resources:
    limits:
      cpu: '2'
      memory: 4G
    requests:
      cpu: '1'
      memory: 4G
  storageSize: 120Gi
indexedSearch:
  replicaCount: 1
  resources:
    limits:
      cpu: '4'
      memory: 8G
    requests:
      cpu: '2'
      memory: 4G
  storageSize: 60Gi
indexedSearchIndexer:
  replicaCount: 1
  resources:
    limits:
      cpu: '2'
      memory: 4G
    requests:
      cpu: '1'
      memory: 2G
minio:
  replicaCount: 1
  resources:
    limits:
      cpu: '1'
      memory: 500M
    requests:
      cpu: '0.5'
      memory: 200M
pgsql:
  replicaCount: 1
  resources:
    limits:
      cpu: '2'
      memory: 2G
    requests:
      cpu: '1'
      memory: 1G
preciseCodeIntel:
  replicaCount: 1
  resources:
    limits:
      cpu: '1'
      memory: 2G
    requests:
      cpu: 200m
      memory: 1G
redisCache:
  replicaCount: 1
  resources:
    limits:
      cpu: '1'
      memory: 1G
    requests:
      cpu: '0.5'
      memory: 500M
redisStore:
  replicaCount: 1
  resources:
    limits:
      cpu: '1'
      memory: 2G
    requests:
      cpu: '0.5'
      memory: 1G
searcher:
  replicaCount: 1
  resources:
    limits:
      cpu: '1'
      ephemeral-storage: 3G
      memory: 1G
    requests:
      cpu: 500m
      ephemeral-storage: 2G
      memory: 500M
symbols:
  replicaCount: 1
  resources:
    limits:
      cpu: '2'
      ephemeral-storage: 24G
      memory: 2G
    requests:
      cpu: 500m
      ephemeral-storage: 20G
      memory: 500M
syntectServer:
  replicaCount: 1
  resources:
    limits:
      cpu: '2'
      memory: 3G
    requests:
      cpu: 500m
      memory: 2G
worker:
  replicaCount: 1
  resources:
    limits:
      cpu: '2'
      memory: 4G
    requests:
      cpu: 500m
      memory: 2G
codeIntelDB:
  # -- Enable `codeintel-db` PostgreSQL server
  enabled: true
  auth:
    # -- Name of existing secret to use for CodeIntel credentials
    # The secret must contain the keys `user`, `password`, `database`, `host` and `port`.
    # `auth.user`, `auth.password`, etc. are ignored if this is enabled
    existingSecret: ""
    # -- Sets codeintel-db database name
    database: "sg"
    # -- Sets codeintel-db host
    host: "codeintel-db"
    # -- Sets codeintel-db username
    user: "sg"
    # -- Sets codeintel-db password
    password: "password"
    # -- Sets codeintel-db port
    port: "5432"
  # -- Name of existing ConfigMap for `codeintel-db`. It must contain a `postgresql.conf` key
  existingConfig: ""
  # -- Additional PostgreSQL configuration. This will override or extend our default configuration.
  # Notes: This is expecting a multiline string.
  # Learn more from our [recommended PostgreSQL configuration](https://docs.sourcegraph.com/admin/config/postgres-conf) and [PostgreSQL documentation](https://www.postgresql.org/docs/12/config-setting.html)
  additionalConfig: ""
  image:
    # -- Docker image name for the `codeintel-db` image
    name: "codeintel-db"
  # -- Security context for the `codeintel-db` container,
  # learn more from the [Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container)
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsUser: 999
    runAsGroup: 999
    readOnlyRootFilesystem: true
  # -- Configuration for the `pgsql-exporter` sidecar container
  postgresExporter: {}
  # -- Name used by resources. Does not affect service names or PVCs.
  name: "codeintel-db"
  # -- Resource requests & limits for the `codeintel-db` container,
  # learn more from the [Kubernetes documentation](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/)
  resources:
    limits:
      cpu: "4"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 1Gi
  # -- Security context for the `codeintel-db` pod,
  # learn more from the [Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod)
  podSecurityContext:
    runAsUser: 999
    fsGroup: 999
    fsGroupChangePolicy: "OnRootMismatch"
  serviceAccount:
    # -- Enable creation of ServiceAccount for `codeintel-db`
    create: false
    # -- Name of the ServiceAccount to be created or an existing ServiceAccount
    name: ""
  # -- PVC Storage Request for `codeintel-db` data volume
  storageSize: 200Gi
codeInsightsDB:
  # -- Enable `codeinsights-db` PostgreSQL server
  enabled: true
  auth:
    # -- Name of existing secret to use for Code Insights credentials
    # The secret must contain the keys `user`, `password`, `database`, `host` and `port`.
    # `auth.user`, `auth.password`, etc. are ignored if this is enabled
    existingSecret: ""
    # -- Sets codeinsights-db database name
    database: "postgres"
    # -- Sets codeinsights-db host
    host: "codeinsights-db"
    # -- Sets codeinsights-db username
    user: "postgres"
    # -- Sets codeinsights-db password
    password: "password"
    # -- Sets codeinsights-db port
    port: "5432"
  # -- Environment variables for the `codeinsights-db` container
  env: {}
  # -- Name of existing ConfigMap for `codeinsights-db`. It must contain a `postgresql.conf` key.
  existingConfig: "" # Name of an existing configmap
  # -- Additional PostgreSQL configuration. This will override or extend our default configuration.
  # Notes: This is expecting a multiline string.
  # Learn more from our [recommended PostgreSQL configuration](https://docs.sourcegraph.com/admin/config/postgres-conf) and [PostgreSQL documentation](https://www.postgresql.org/docs/12/config-setting.html)
  additionalConfig: ""
  image:
    # -- Docker image name for the `codeinsights-db` image
    name: "codeinsights-db"
  # -- Security context for the `codeinsights-db` container,
  # learn more from the [Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container)
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsUser: 70
    runAsGroup: 70
    readOnlyRootFilesystem: true
  init:
    # -- Security context for the `alpine` initContainer,
    # learn more from the [Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container)
    containerSecurityContext:
      allowPrivilegeEscalation: false
      runAsUser: 70
      runAsGroup: 70
      readOnlyRootFilesystem: true
  # -- Configuration for the `pgsql-exporter` sidecar container
  postgresExporter: {}
  # -- Name used by resources. Does not affect service names or PVCs.
  name: "codeinsights-db"
  # -- Resource requests & limits for the `codeinsights-db` container,
  # learn more from the [Kubernetes documentation](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/)
  resources:
    limits:
      cpu: "4"
      memory: 2Gi
    requests:
      cpu: "1"
      memory: 500Mi
  # -- Security context for the `codeinsights-db` pod,
  # learn more from the [Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod)
  podSecurityContext:
    runAsUser: 70
    fsGroup: 70
    fsGroupChangePolicy: "OnRootMismatch"
  serviceAccount:
    # -- Enable creation of ServiceAccount for `codeinsights-db`
    create: false
    # -- Name of the ServiceAccount to be created or an existing ServiceAccount
    name: ""
  # -- PVC Storage Request for `codeinsights-db` data volume
  storageSize: 200Gi
```
