### ISSUE TITLE
Frontend pdb is missing `matchLabels:` for selector

### ISSUE THREAD

**Issue by BadLiveware** [sourcegraph/deploy-sourcegraph-helm#355]
https://github.com/sourcegraph/deploy-sourcegraph-helm/blob/f35310caa4d7514f892f7e7c1a6f753ca6b2918b/charts/sourcegraph/templates/frontend/sourcegraph-frontend.PodDisruptionBudget.yaml#L1-L11

This is missing matchLabels and should look like

```yaml
 {{- if .Values.frontend.podDisruptionBudget }} 
 apiVersion: policy/v1 
 kind: PodDisruptionBudget 
 metadata: 
   name: sourcegraph-frontend 
 spec: 
   {{- toYaml .Values.frontend.podDisruptionBudget | nindent 2 }} 
   selector: 
     matchLabels: ## <<<
       {{- include "sourcegraph.selectorLabels" . | nindent 4 }} 
       app: sourcegraph-frontend 
 {{- end }} 
```
