### ISSUE TITLE
redis-cli readinessProbe should respect redis password authentication when enabled

### ISSUE THREAD

**Issue by loujar** [sourcegraph/deploy-sourcegraph-helm#457]
## Problem
Recent changes to the redis pods' (both `redis-cache` and `redis-store`) `readinessProbe` has not accounted for helm deployments of Sourcegraph that have configured a redis password as defined in our [docs](https://sourcegraph.com/docs/admin/how-to/redis_configmap).

This results in the following observed behavior:
1. Both the `redis-cache` and `redis-store` pods fail their `readinessProbe`, with the following error shown in the `kubectl describe pod <redis-cache pod | redis-store pod>` Events output: `(error) NOAUTH Authentication required.`
2. The `redis-cache` and `redis-store` pods show `1/2` containers running in `kubectl get pods` output (`redis-exporter` is running)
3. The `sourcegraph-frontend` container is unable to connect to either redis instance, resulting in the frontend failing to serve up requests to users. Error observed in `sourcegraph-frontend` container logs:
```
!!!!!  Redis Store is required
	Problem: Redis "Store" is unavailable or misconfigured
	Error: dial tcp 172.17.130.59:6379: connect: connection refused
	Possible fix: Start a Redis server listening at port
		redis://:<pwd>@redis-store:6379
	Skip this check by setting the env var SRC_SKIP_REQS="Redis Store"
		(separate multiple entries with spaces). Note: Sourcegraph may not
		function properly without Redis Store.
 !!!!!  Redis Cache is required
	Problem: Redis "Cache" is unavailable or misconfigured
	Error: dial tcp 172.17.138.103:6379: connect: connection refused
	Possible fix: Start a Redis server listening at port
		redis://:<pwd>@redis-cache:6379
	Skip this check by setting the env var SRC_SKIP_REQS="Redis Cache"
		(separate multiple entries with spaces). Note: Sourcegraph may not
		function properly without Redis Cache.
```

## Proposed Solution
The new redis `readinessProbe` uses the `redis-cli ping` check:
```yaml
    readinessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - |
          #!/bin/bash
          response=$(
            redis-cli ping
          )
          if [ "$response" != "PONG" ]; then
            echo "$response"
            exit 1
          fi
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
```
If we chose to continue using `redis-cli`, we can leverage the `-a` [flag](https://redis.io/docs/latest/develop/connect/cli/#host-port-password-and-database) to specify the necessary password, but we will need to solve for pulling the password from the mounted `/etc/redis/redis.conf` file.
